Bonilla-Adrian/CS4311_INFILTR8_1DecafCats_Fall2024

INFILTR8/src/lib/neo4j.js
INFILTR8/src/routes/login/+page.svelte
INFILTR8/src/routes/login/query/+server.js

Set up a simple login that ask the database for user infomation and checks it against the inputed values

Sample-login

---

INFILTR8/src/lib/components/Navbar.svelte
INFILTR8/src/lib/components/Toast.svelte
INFILTR8/src/lib/stores.js
INFILTR8/src/lib/stores/notifications.js
INFILTR8/src/lib/utils.js
INFILTR8/src/routes/+layout.svelte

Fixed some UI bugs with Navbar, Improved Navbar, Implemented notifications for System

Notifications

---

INFILTR8/src/lib/components/Colorblind.svelte
INFILTR8/src/routes/+layout.svelte

Colorblind component and consistent among all pages

Colorblind component finished

---

INFILTR8/src/routes/analysis/+page.svelte

Complete fixing the dark mode as well it's format for the analysis page including their graph and summary section

Remove unused import and logger instantiation

---

INFILTR8/backend/app.py
INFILTR8/src/routes/dashboard/+page.svelte

of the project upload and creation

back to front connection

---

INFILTR8/backend/app.py
INFILTR8/src/routes/dashboard/+page.svelte

timezone fix for the logging

---

INFILTR8/src/routes/dashboard/+page.svelte

showing the project to the user

---

INFILTR8/backend/app.py
INFILTR8/src/routes/report/+page.svelte

Added Logging functionality for the Reports IPs,
please review changes made in Reports page: handleExport(). Please review changes made in backend app.py: app.route

Reports Logging

---

INFILTR8/src/routes/settings/+page.svelte

logs for settings

---

INFILTR8/src/routes/project/+page.svelte

logs project click in each example

logs to project, click in each example

---

INFILTR8/backend/app.py
INFILTR8/backend/logs/logmanager.py
INFILTR8/src/routes/analysis/+page.svelte

.log format and user session made for logs

log user session fixed again and format changed to .log

---

INFILTR8/backend/app.py
INFILTR8/src/routes/project/+page.svelte

analysis fix again and remove of selected IPs

---

INFILTR8/src/routes/+layout.svelte
INFILTR8/src/routes/dashboard/+page.svelte
INFILTR8/src/routes/project/+page.svelte

Dashboard refactor

---

INFILTR8/backend/app.py
INFILTR8/backend/classes/project.py
INFILTR8/backend/classes/user_service.py
INFILTR8/src/routes/dashboard/+page.svelte
INFILTR8/src/routes/login/+page.svelte

admin reset functionality

---

INFILTR8/src/routes/report/+page.svelte

Reports branch

---

INFILTR8/src/routes/login/+page.svelte

Bug fix on admin functionality

---

INFILTR8/backend/app.py
INFILTR8/backend/classes/analysis.py
INFILTR8/backend/classes/nessus_upload.py
INFILTR8/src/lib/stores.js
INFILTR8/src/routes/project/+page.svelte
INFILTR8/vite.config.ts
README.md

fixed backend issues and different flow problems with project create

Erik-flow-fixes

---

INFILTR8/backend/app.py
INFILTR8/backend/classes/project.py
INFILTR8/src/routes/project/+page.svelte

Delete project tested and works. will delete the analysis nodes that are attached to it

added delete project from backend to frontend

---

INFILTR8/src/routes/report/+page.svelte

Created filter for each data set, added sorting for min max severity, default selected all datasets in export, fixed darkmode inside cells, added e.g. to filters

Report filtering

---

INFILTR8/backend/app.py
INFILTR8/backend/classes/analysis.py
INFILTR8/backend/classes/parser.py
INFILTR8/backend/classes/project.py
INFILTR8/src/lib/stores.js
INFILTR8/src/routes/dashboard/+page.svelte
INFILTR8/src/routes/project/+page.svelte

unique Archetypes fetched from route "/flask-api/get-archetypes-from-nessus"
and sent to "process-nessus" route to start analysis with selectedArchetypes

Archetypes2

---

INFILTR8/backend/classes/nessus_upload.py
INFILTR8/backend/classes/project.py

cleaning up all the different things that are affected by mult files
